name: Dogs spa CI/CD
run-name: Dogs spa pipeline
on: 
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn jest

      - name: Run cypress tests
        run: yarn test:cy:run